#!/bin/bash
gcc --version
echo "minimum required version of GNU gcc: 4.8.2"
cd ./src
echo -e "fluid_solver: compilation started"
make all
echo -e "fluid_solver: complitaion completed"
make clean
mv fluid_solver ../fluid_solver